### ISSUE TITLE
Problem with custom TALES extension

### ISSUE THREAD

**Issue by tflorac** [wichert/lingua#54]
Hi,
I'm using Lingua (3.8) with Python (3.4) on a Pyramid package using Chameleon templates.
I have created a custom "provider:" TALES expressions, which works perfectly with Chameleon but generates an error in Lingua.
My PT code is as follow:

    ...
    <tal:var content="structure provider:pyams.toolbar" />
    ...

Lingua error is: Aborting due to Python syntax error in ./src/templates/table.pt[11]: (python:pyams.toolbar)

Any idea?

Best regards,
Thierry

**Comment by wichert** [comment]
This was fixed with #55
