### ISSUE TITLE
Aborting due to parse error, with a dict as a method argument (in chameleon)

### ISSUE THREAD

**Issue by betabug-sw** [wichert/lingua#62]
Creating a chameleon page template, with only this content:
```
${some_method(_('abc'), {'a':'b'})}
```

and running ``pot-create -o failure.pot minimal_failure.pt``, results in an error:
```
Aborting due to parse error in ./minimal_failure.pt[2]: some_method(_('abc'), {'a':'b'
```

(Yes, the error stops right there, the closing } of the dict is not there.)

If we change our example to replace the dict with a dict(), like this:
```
${some_method(_('abc'), dict(a='b'))}
```
Then the parsing will continue successfully.

(lingua==3.10, Chameleon==2.22, pyramid==1.6a2)

**Comment by wichert** [comment]
I've pushed a fix. Can you test if this resolved your problem?

**Comment by betabug-sw** [comment]
Thank you! This fix resolved the problem!
