### ISSUE TITLE
Multiple i18ndomains

### ISSUE THREAD

**Issue by rnixx** [wichert/lingua#65]
Referring to https://github.com/collective/i18ndude/issues/22#issuecomment-143675824

> at some point lingua had problems handling multiple i18ndomains in one run. but maybe this was solved meanwhile.

@wichert can you confirm this?

**Comment by wichert** [comment]
I'm not aware of any problems. I've also been using lingua in projects which use multiple domains without problems, so I'm quite confident that works as expected.

I'll followup on the i18ndude ticket, so I'm going to close this ticket.
