### ISSUE TITLE
Temp file can not be renamed on Windows

### ISSUE THREAD

**Issue by kalbermattenm** [wichert/lingua#81]
I updated lingua from version 4.6 to 4.9 (Python 2.7 on Windows 7) and since then it is not working correctly anymore.

I always get this error:

`WindowsError: [Error 32] The process cannot access the file beacause it is being used by another process.`

Apparently, the `tmpfile`is not correctly closed and the system still thinks the file is being used, thus `os.rename` (https://github.com/wichert/lingua/blob/master/src/lingua/extract.py#L235) throws this error.

Moreover, just before `os.rename` I tried that:
```python
f = open(tmpfile)
f.close()
```
And I get exactly the same error, but for the `f = open(tmpfile)` command...

**Comment by wichert** [comment]
Can you try doing `os.close(fd)` just before the rename? I think that will fix it. I don't have access to Windows myself, so I can't test that. The source should look like this:

```python
      (fd, tmpfile) = tempfile.mkstemp(dir=os.path.dirname(filename), text=True)
      catalog.save(tmpfile)
      os.close(fd)
      os.rename(tmpfile, filename)
```

**Comment by kalbermattenm** [comment]
That did the trick, thanks ! I did not get that `fd` was the file... sorry....

Do you want me to submit a PR ?

**Comment by wichert** [comment]
I already have a commit ready here; so there is no need to submit a PR. Thanks for the offer though!  I am currently traveling, but will try to get a new release out soon.

**Comment by kalbermattenm** [comment]
OK thanks a lot for the fix and the future release ! Safe travels ;-)
